"""Generates a deep-dive Quantitative Intelligence Report using AI.
Analyzes the results of the latest market scan.
"""

import logging
import os
import sys
from pathlib import Path
from datetime import datetime
from typing import List, Dict

# Add project root to path
sys.path.append(str(Path(__file__).parent))

from src.ai.ai_agent import AIAgent

# Setup Logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger("AIReport")

def generate_deep_dive():
    logger.info("Starting AI Deep-Dive Report Generation...")
    
    # 1. Locate Latest Scan
    scan_file = Path("./data/daily_scans/latest_optimized_scan.txt")
    if not scan_file.exists():
        logger.error("No scan results found in data/daily_scans/latest_optimized_scan.txt")
        return

    with open(scan_file, 'r', encoding='utf-8') as f:
        scan_content = f.read()

    # 2. Extract Top Picks (Simple parsing for AI context)
    # We'll take the first 3000 chars of the scan to get stats and top buys
    ai_context = scan_content[:4000]

    # 3. Generate report body (AI-first with deterministic fallback)
    ai = AIAgent()
    logger.info("Sending data to AI for deep-dive analysis...")
    report = ai.generate_deep_dive_report(ai_context)

    # 4. Save Report
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    output_dir = Path("./data/reports")
    output_dir.mkdir(parents=True, exist_ok=True)
    output_path = output_dir / f"quantum_intelligence_report_{timestamp}.md"
    
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write("# 🔬 Quantum Intelligence Executive Brief\n")
        f.write(f"**Analysis Date:** {datetime.now().strftime('%B %d, %Y')}\n\n")
        f.write(report)
        f.write(f"\n\n---\n*Generated by AlphaIntelligence AI Engine v2.0*")

    logger.info(f"Report successfully generated and saved to {output_path}")
    print(f"\nSUCCESS: AI Report generated at {output_path}")

if __name__ == "__main__":
    generate_deep_dive()
